# Generated by Django 5.1.1 on 2024-10-09 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_alter_book_isbn"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="isbn",
            new_name="information",
        ),
    ]
